frr version 8.5
frr defaults traditional
hostname leaf2
service integrated-vtysh-config
!
interface eth1
 ip address 10.0.21.2/30
!
interface eth2
 ip address 10.0.22.2/30
!
interface lo
 ip address 10.10.2.1/32
!
ip prefix-list ALLOW-ALL seq 10 permit 0.0.0.0/0 le 32
!
route-map ALLOW-ALL permit 10
 match ip address prefix-list ALLOW-ALL
!
router bgp 65102
 bgp router-id 10.10.2.1
 neighbor 10.0.21.1 remote-as 65001
 neighbor 10.0.22.1 remote-as 65002
 !
 address-family ipv4 unicast
  network 10.10.2.1/32

  neighbor 10.0.21.1 activate
  neighbor 10.0.21.1 route-map ALLOW-ALL in
  neighbor 10.0.21.1 route-map ALLOW-ALL out

  neighbor 10.0.22.1 activate
  neighbor 10.0.22.1 route-map ALLOW-ALL in
  neighbor 10.0.22.1 route-map ALLOW-ALL out
 exit-address-family
!