frr version 8.5
frr defaults traditional
hostname leaf1
service integrated-vtysh-config
!
interface eth1
 ip address 10.0.11.2/30
!
interface eth2
 ip address 10.0.12.2/30
!
interface lo
 ip address 10.10.1.1/32
!
ip prefix-list ALLOW-ALL seq 10 permit 0.0.0.0/0 le 32
!
route-map ALLOW-ALL permit 10
 match ip address prefix-list ALLOW-ALL
!
route-map PREFER-SPINE2 permit 10
 set local-preference 150
!
router bgp 65101
 bgp router-id 10.10.1.1
 neighbor 10.0.11.1 remote-as 65001
 neighbor 10.0.12.1 remote-as 65002
 !
 address-family ipv4 unicast
  network 10.10.1.1/32
  neighbor 10.0.11.1 activate
  neighbor 10.0.11.1 route-map ALLOW-ALL in
  neighbor 10.0.11.1 route-map ALLOW-ALL out

  neighbor 10.0.12.1 activate
  neighbor 10.0.12.1 route-map PREFER-SPINE2 in
  neighbor 10.0.12.1 route-map ALLOW-ALL out
 exit-address-family
!