all:
  children:

    leaves:
      hosts:

        leaf1:
          container_name: clab-bgp-automation-leaf1
          bgp_asn: 65101

        leaf2:
          container_name: clab-bgp-automation-leaf2
          bgp_asn: 65102

    spines:
      hosts:

        spine1:
          container_name: clab-bgp-automation-spine1
          bgp_asn: 65001

        spine2:
          container_name: clab-bgp-automation-spine2
          bgp_asn: 65002